Exercise 1: Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix.

In [4]:
import numpy as np

arr = np.arange(1, 11)

reshaped_arr = arr.reshape((2, 5))

print(reshaped_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]



Exercise 2: Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index.

In [16]:
import numpy as np

arr = np.arange(1, 21)

arr_elements = arr[5:16]

print(arr_elements)


[ 6  7  8  9 10 11 12 13 14 15 16]


Exercise 3: Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}. Then, add a new item to the series with the key 'pears' and the value 4.

In [23]:
import pandas as pd

fruits = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})

fruits['pears'] = 4

fruits.name = "Fruits"

print(fruits)

apples     3
bananas    2
oranges    1
pears      4
Name: Fruits, dtype: int64


Exercise 4: Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data.

In [28]:
import pandas as pd

data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Helen', 'Ian', 'Jane'],
    'Age': [25, 30, 22, 35, 28, 33, 26, 24, 29, 31],
    'Gender': ['Female', 'Male', 'Male', 'Male', 'Female', 'Male', 'Female', 'Female', 'Male', 'Female']
}

df = pd.DataFrame(data)

print(df)

      Name  Age  Gender
0    Alice   25  Female
1      Bob   30    Male
2  Charlie   22    Male
3    David   35    Male
4      Eva   28  Female
5    Frank   33    Male
6    Grace   26  Female
7    Helen   24  Female
8      Ian   29    Male
9     Jane   31  Female


Exercise 5: Add a new column to the data frame created in question 1, called occupation. The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe.

In [31]:
occupations = ['Programmer', 'Manager', 'Analyst'] * 3 + ['Programmer']  
df['occupation'] = occupations
print(df)

      Name  Age  Gender  occupation
0    Alice   25  Female  Programmer
1      Bob   30    Male     Manager
2  Charlie   22    Male     Analyst
3    David   35    Male  Programmer
4      Eva   28  Female     Manager
5    Frank   33    Male     Analyst
6    Grace   26  Female  Programmer
7    Helen   24  Female     Manager
8      Ian   29    Male     Analyst
9     Jane   31  Female  Programmer


Exercise 6: Select the rows of the dataframe where the age is greater than or equal to 30.

In [36]:
filtered_df = df[df['Age'] >= 30]

print(filtered_df)

    Name  Age  Gender  occupation
1    Bob   30    Male     Manager
3  David   35    Male  Programmer
5  Frank   33    Male     Analyst
9   Jane   31  Female  Programmer


Exercise 7: Convert this dataframe to a csv file and read that csv file, finally display the contents.

In [41]:
import pandas as pd

df.to_csv('DataFrameAssignment.csv', index=False)

df_from_csv = pd.read_csv('DataFrameAssignment.csv')

print(df_from_csv)

      Name  Age  Gender  occupation
0    Alice   25  Female  Programmer
1      Bob   30    Male     Manager
2  Charlie   22    Male     Analyst
3    David   35    Male  Programmer
4      Eva   28  Female     Manager
5    Frank   33    Male     Analyst
6    Grace   26  Female  Programmer
7    Helen   24  Female     Manager
8      Ian   29    Male     Analyst
9     Jane   31  Female  Programmer
